delete from BuildingModifiers where BuildingType = 'BUILDING_PHANTA_TEMPLE_OF_HEAVEN' and ModifierId in (
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_FOOD_BONUS',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_CULTURE_BONUS',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_FOOD_BONUS_AGRI',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_CULTURE_BONUS_AGRI'
);
delete from PolicyModifiers where ModifierId in (
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_FOOD_BONUS',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_CULTURE_BONUS',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_FOOD_BONUS_AGRI',
  'MODFEAT_PHANTA_TEMPLE_OF_HEAVEN_CULTURE_BONUS_AGRI'
);
update Buildings set Description = 'LOC_HD_BUILDING_PHANTA_TEMPLE_OF_HEAVEN_DESCRIPTION' where BuildingType = 'BUILDING_PHANTA_TEMPLE_OF_HEAVEN';