insert or replace into EnglishText (Tag, Text) values
  -- ToolTip
  ("LOC_BUILDING_PLAYER_RESOURCE_TOTAL_TOOLTIP_TEXT",               "Player has {1_Amount} related Resources in total"),
  ("LOC_BUILDING_PLAYER_RESOURCE_CLASSIFICATION_TOOLTIP_TEXT",      "[ICON_BULLET] {1_Amount} {2_Name} Resources"),

  ("LOC_BUILDING_CLASSIFICATION_TRANSPORTATION_NAME",               "Transportation Building"),

  ("LOC_DISTRICT_CLASSIFICATION_TRANSPORTATION_NAME",               "Transportation District"),
  ("LOC_DISTRICT_CLASSIFICATION_HYDRAULIC_NAME",                    "Hydraulic District"),
  ("LOC_DISTRICT_CLASSIFICATION_ENTERTAINING_NAME",                 "Entertaining District"),

  ("LOC_IMPROVEMENT_CLASSIFICATION_BASIC_NAME",                     "Basic Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_WATER_NAME",                     "Water-based Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_COMMON_NAME",                    "Common Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_UNIQUE_NAME",                    "Unique Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_CITYSTATE_NAME",                 "City-state Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_AGRARIAN_NAME",                  "Agrarian Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_EXPLOITATIVE_NAME",              "Exploitative Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_EDUCATIONAL_NAME",               "Educational Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_MILITARISTIC_NAME",              "Militaristic Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_COMMERCIAL_NAME",                "Commercial Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_RESIDENTIAL_NAME",               "Residential Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_RELIGIOUS_NAME",                 "Religious Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_LANDSCAPE_NAME",                 "Landscape Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_ENTERTAINING_NAME",              "Entertaining Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_HYDRAULIC_NAME",                 "Hydraulic Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_TRANSPOTATION_NAME",             "Transportation Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_RENEWABLE_NAME",                 "Renewables Improvement"),
  ("LOC_IMPROVEMENT_CLASSIFICATION_OTHER_NAME",                     "Other Improvement"),

  ("LOC_MOMENT_CLASSIFICATION_EXPLORATION_NAME",                    "Exploration Moment"),
  ("LOC_MOMENT_CLASSIFICATION_MILITARY_NAME",                       "Military Moment"),
  ("LOC_MOMENT_CLASSIFICATION_DEVELOPMENT_NAME",                    "Development Moment"),
  ("LOC_MOMENT_CLASSIFICATION_DIPLOMACY_NAME",                      "Diplomacy Moment"),
  ("LOC_MOMENT_CLASSIFICATION_RELIGION_NAME",                       "Religion Moment"),
  ("LOC_MOMENT_CLASSIFICATION_CIVILIZATION_FIRST_NAME",             "Civilization's First Moment"),
  ("LOC_MOMENT_CLASSIFICATION_WORLD_FIRST_NAME",                    "World's First Moment"),
  ("LOC_MOMENT_CLASSIFICATION_OTHER_NAME",                          "Other Moment"),

  ("LOC_RESOURCE_PARENT_CLASSIFICATION_HD_USAGE_NAME",              "Usage"),
  ("LOC_RESOURCE_PARENT_CLASSIFICATION_HD_IMPROVEMENT_NAME",        "Improvement"),
  ("LOC_RESOURCE_PARENT_CLASSIFICATION_HD_OTHER_NAME",              "Others"),
  ("LOC_RESOURCE_PARENT_CLASSIFICATION_HD_THIRDPARTY_NAME",         "Third Party"),

  ("LOC_RESOURCE_CLASSIFICATION_HD_CROPS_NAME",                     "Crops"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_AGRICULTURE_NAME",               "Agriculture"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_CUISINE_NAME",                   "Cuisine"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_FRUIT_NAME",                     "Fruit"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_VEGETABLE_NAME",                 "Vegetable"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_BREWING_NAME",                   "Brewing"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_BEVERAGE_NAME",                  "Beverage"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_OIL_NAME",                       "Oil"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_LEATHER_NAME",                   "Leather"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_CLOTH_NAME",                     "Cloth"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_CONSTRUCTION_NAME",              "Construction"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_FUEL_NAME",                      "Fuel"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_CHEMISTRY_NAME",                 "Chemistry"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_METALLURGY_NAME",                "Metallurgy"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_MINTING_NAME",                   "Minting"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_TRANSIT_NAME",                   "Transit"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_SEASONING_NAME",                 "Seasoning"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_SEAFOOD_NAME",                   "Seafood"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_MARINE_PRODUCTS_NAME",           "Marine Products"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_SEA_BEAST_NAME",                 "Sea Beast"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_CELEBRATION_NAME",               "Celebration"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_MEDICINE_NAME",                  "Medicine"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_STATIONERY_NAME",                "Stationery"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_ART_NAME",                       "Art"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_DECORATION_NAME",                "Decoration"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_ORNAMENTAL_NAME",                "Ornamental"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_BEAST_NAME",                     "Beast"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_HOUSEHOLD_NAME",                 "Household"),

  ("LOC_RESOURCE_CLASSIFICATION_HD_TOYS_NAME",                      "Toys"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_COSMETICS_NAME",                 "Cosmetics"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_JEANS_NAME",                     "Jeans"),
  ("LOC_RESOURCE_CLASSIFICATION_HD_PERFUME_NAME",                   "Perfume"),

  ("LOC_RESOURCE_CLASSIFICATION_BIOLOGICAL_NAME",                   "Biological"),
  ("LOC_RESOURCE_CLASSIFICATION_MINERAL_NAME",                      "Mineral"),

  ("LOC_RESOURCE_CLASSIFICATION_CIVILIZATION_NAME",                 "Civilization Unique"),
  ("LOC_RESOURCE_CLASSIFICATION_CITYSTATE_NAME",                    "City-state Exclusive");

insert or replace into LocalizedText (Language, Tag, Text) values
  -- ToolTip
  ("zh_Hans_CN", "LOC_BUILDING_PLAYER_RESOURCE_TOTAL_TOOLTIP_TEXT",               "玩家共拥有{1_Amount}个相关资源"),
  ("zh_Hans_CN", "LOC_BUILDING_PLAYER_RESOURCE_CLASSIFICATION_TOOLTIP_TEXT",      "[ICON_BULLET]{1_Amount}个{2_Name}资源"),

  ("zh_Hans_CN", "LOC_BUILDING_CLASSIFICATION_TRANSPORTATION_NAME",               "交通设施建筑"),

  ("zh_Hans_CN", "LOC_DISTRICT_CLASSIFICATION_TRANSPORTATION_NAME",               "交通设施区域"),
  ("zh_Hans_CN", "LOC_DISTRICT_CLASSIFICATION_HYDRAULIC_NAME",                    "水利工程区域"),
  ("zh_Hans_CN", "LOC_DISTRICT_CLASSIFICATION_ENTERTAINING_NAME",                 "娱乐活动区域"),

  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_BASIC_NAME",                     "基础改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_WATER_NAME",                     "水上改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_COMMON_NAME",                    "通用改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_UNIQUE_NAME",                    "特色改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_CITYSTATE_NAME",                 "城邦改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_AGRARIAN_NAME",                  "农业生产改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_EXPLOITATIVE_NAME",              "工业开发改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_EDUCATIONAL_NAME",               "研究教育改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_MILITARISTIC_NAME",              "军事屯驻改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_COMMERCIAL_NAME",                "贸易往来改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_RESIDENTIAL_NAME",               "民居宅邸改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_RELIGIOUS_NAME",                 "宗教场所改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_LANDSCAPE_NAME",                 "旅游景观改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_ENTERTAINING_NAME",              "娱乐活动改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_HYDRAULIC_NAME",                 "水利工程改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_TRANSPOTATION_NAME",             "交通设施改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_RENEWABLE_NAME",                 "清洁能源改良"),
  ("zh_Hans_CN", "LOC_IMPROVEMENT_CLASSIFICATION_OTHER_NAME",                     "其他改良"),

  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_EXPLORATION_NAME",                    "探索类历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_MILITARY_NAME",                       "军事类历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_DEVELOPMENT_NAME",                    "发展类历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_DIPLOMACY_NAME",                      "外交类历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_RELIGION_NAME",                       "宗教类历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_CIVILIZATION_FIRST_NAME",             "文明首次历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_WORLD_FIRST_NAME",                    "世界首次历史时刻"),
  ("zh_Hans_CN", "LOC_MOMENT_CLASSIFICATION_OTHER_NAME",                          "其他历史时刻"),

  ("zh_Hans_CN", "LOC_RESOURCE_PARENT_CLASSIFICATION_HD_USAGE_NAME",              "用途"),
  ("zh_Hans_CN", "LOC_RESOURCE_PARENT_CLASSIFICATION_HD_IMPROVEMENT_NAME",        "按改良分类"),
  ("zh_Hans_CN", "LOC_RESOURCE_PARENT_CLASSIFICATION_HD_OTHER_NAME",              "其他分类"),
  ("zh_Hans_CN", "LOC_RESOURCE_PARENT_CLASSIFICATION_HD_THIRDPARTY_NAME",         "第三方分类"),

  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CROPS_NAME",                     "庄稼"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_AGRICULTURE_NAME",               "农用"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CUISINE_NAME",                   "美食"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_FRUIT_NAME",                     "水果"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_VEGETABLE_NAME",                 "蔬菜"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_BREWING_NAME",                   "酿造"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_BEVERAGE_NAME",                  "饮料"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_OIL_NAME",                       "油料"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_LEATHER_NAME",                   "皮革"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CLOTH_NAME",                     "服装"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CONSTRUCTION_NAME",              "建造"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_FUEL_NAME",                      "燃料"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CHEMISTRY_NAME",                 "化学"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_METALLURGY_NAME",                "冶金"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_MINTING_NAME",                   "货币"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_TRANSIT_NAME",                   "运载"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_SEASONING_NAME",                 "调料"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_SEAFOOD_NAME",                   "海鲜"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_MARINE_PRODUCTS_NAME",           "海货"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_SEA_BEAST_NAME",                 "海兽"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_CELEBRATION_NAME",               "庆典"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_MEDICINE_NAME",                  "医药"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_STATIONERY_NAME",                "文具"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_ART_NAME",                       "艺术"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_DECORATION_NAME",                "饰品"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_ORNAMENTAL_NAME",                "花木"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_BEAST_NAME",                     "珍兽"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_HOUSEHOLD_NAME",                 "家居"),

  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_TOYS_NAME",                      "玩具"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_COSMETICS_NAME",                 "化妆品"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_JEANS_NAME",                     "牛仔裤"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_HD_PERFUME_NAME",                   "香水"),

  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_BIOLOGICAL_NAME",                   "生物类"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_MINERAL_NAME",                      "矿产类"),

  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_CIVILIZATION_NAME",                 "文明特色"),
  ("zh_Hans_CN", "LOC_RESOURCE_CLASSIFICATION_CITYSTATE_NAME",                    "城邦专属");