-- 新着力点
insert or replace into Types
	(Type,								                        Kind)
values
  -- 翻译运动
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',			'KIND_MOMENT_OUTCOME'),
  -- 繁荣之路
	('COMMEMORATION_HD_FLOURSHING_ROAD',					'KIND_MOMENT_OUTCOME'),
  -- 筚路蓝缕
	('COMMEMORATION_HD_DOMESTIC_ASSART',					'KIND_MOMENT_OUTCOME'),
  -- 信仰之战
	('COMMEMORATION_HD_RELIGIOUS_WAR',				    'KIND_MOMENT_OUTCOME'),
  -- 开明专制
	('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		'KIND_MOMENT_OUTCOME'),
  -- 宗教改革
	('COMMEMORATION_HD_RELIGIOUS_REFORM',		      'KIND_MOMENT_OUTCOME'),
  -- 浪漫主义
	('COMMEMORATION_HD_ROMANTICISM',		          'KIND_MOMENT_OUTCOME'),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',		'KIND_MOMENT_OUTCOME');

insert or replace into CommemorationTypes
	(CommemorationType, CategoryDescription, GoldenAgeBonusDescription, NormalAgeBonusDescription, DarkAgeBonusDescription, MinimumGameEra, MaximumGameEra)
values
	-- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_DARK_AGE',
  'ERA_RENAISSANCE',
  'ERA_RENAISSANCE'),
	-- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_DARK_AGE',
  'ERA_RENAISSANCE',
  'ERA_RENAISSANCE'),
	-- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM',
  'LOC_MOMENT_CATEGORY_ROMANTICISM',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_DARK_AGE',
  'ERA_INDUSTRIAL',
  'ERA_MODERN'),
	-- 科学革命
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_DARK_AGE',
  'ERA_INDUSTRIAL',
  'ERA_ATOMIC');

-- 着力点时代改动
  -- 自由探索(自然哲学) 百花齐放(轴心时代) 雄伟壮丽 布道者的远行(光荣胜利)
update CommemorationTypes set MinimumGameEra = 'ERA_CLASSICAL', MaximumGameEra = 'ERA_CLASSICAL'
  where CommemorationType in ('COMMEMORATION_SCIENTIFIC', 'COMMEMORATION_CULTURAL', 'COMMEMORATION_INFRASTRUCTURE', 'COMMEMORATION_RELIGIOUS');
  -- 货币改革(工商业本位)
update CommemorationTypes set MinimumGameEra = 'ERA_RENAISSANCE', MaximumGameEra = 'ERA_RENAISSANCE'
  where CommemorationType in ('COMMEMORATION_ECONOMIC');
  -- 此处有龙
update CommemorationTypes set MinimumGameEra = 'ERA_RENAISSANCE', MaximumGameEra = 'ERA_INDUSTRIAL'
  where CommemorationType in ('COMMEMORATION_EXPLORATION');
  -- 滚滚蒸汽
update CommemorationTypes set MinimumGameEra = 'ERA_INDUSTRIAL', MaximumGameEra = 'ERA_MODERN'
  where CommemorationType in ('COMMEMORATION_INDUSTRIAL');
  -- 全民皆兵
update CommemorationTypes set MinimumGameEra = 'ERA_MODERN', MaximumGameEra = 'ERA_ATOMIC'
  where CommemorationType in ('COMMEMORATION_MILITARY');
  -- 愿你在此 兵不厌诈
update CommemorationTypes set MinimumGameEra = 'ERA_ATOMIC', MaximumGameEra = null
  where CommemorationType in ('COMMEMORATION_TOURISM', 'COMMEMORATION_ESPIONAGE');
  -- 漫天繁星 机器人大战
update CommemorationTypes set MinimumGameEra = 'ERA_INFORMATION', MaximumGameEra = null
  where CommemorationType in ('COMMEMORATION_AERONAUTICAL', 'COMMEMORATION_AUTOMATON');

-- 着力点效果
  -- 自由探索(自然哲学)
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_SCIENTIFIC' and ModifierId not in ('COMMEMORATION_SCIENTIFIC_QUEST', 'COMMEMORATION_SCIENTIFIC_BUILDING_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_CULTURAL' and ModifierId not in ('COMMEMORATION_CULTURAL_QUEST', 'COMMEMORATION_CULTURAL_BUILDING_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_INFRASTRUCTURE' and ModifierId not in ('COMMEMORATION_INFRASTRUCTURE_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_RELIGIOUS';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_ECONOMIC';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_EXPLORATION' and ModifierId = 'COMMEMORATION_EXPLORATION_GA_FOREIGNIDENTITY';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_INDUSTRIAL' and ModifierId = 'COMMEMORATION_INUDSTRIAL_GA_CAMPUS';

insert or replace into CommemorationModifiers
	(CommemorationType,					                  ModifierId)
values
  -- 自由探索(自然哲学)
  ('COMMEMORATION_SCIENTIFIC',                  'COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE'),
  ('COMMEMORATION_SCIENTIFIC',                  'COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE'),
  -- 百花齐放(轴心时代)
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_FAITH'),
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_CULTURE'),
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS'),
  -- 雄伟壮丽
	-- ('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_DISTRICT_PRODUCTION'),
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT'),
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION'),
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS'),
  -- 布道者的远行(光荣胜利)
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT'),
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_UNIT_STRENGTH'),
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD'),
  -- 翻译运动
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD'),
  -- 繁荣之路
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_ECONOMIC_QUEST'),
  -- 筚路蓝缕
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION'),
  -- 信仰之战
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_RELIGIOUS_QUEST'),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT'),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT'),
  -- 工商业本位
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_TRADE_GOLD'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_TRADE_PRODUCTION'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT'),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',         'COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',         'COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS'),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION',		              'COMMEMORATION_EXPLORATION_CIVILIAN_SPEED'),
	('COMMEMORATION_EXPLORATION',		              'COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION'),
  -- 蒸汽滚滚
	('COMMEMORATION_INDUSTRIAL',	                'COMMEMORATION_INUDSTRIAL_INDUSTRIAL_ZONE_BONUS'),
	('COMMEMORATION_INDUSTRIAL',	                'COMMEMORATION_INUDSTRIAL_CAMPUS_BONUS'),
  -- 浪漫主义
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS'),
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS'),
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS'),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS'),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS'),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD'),
  -- 全民皆兵
	('COMMEMORATION_MILITARY',                    'COMMEMORATION_MILITARY_STRENGTH'),
  -- 愿你在此
	('COMMEMORATION_TOURISM',                     'COMMEMORATION_TOURISM_IMPROVEMENT');
  

  -- 信仰之战
insert or replace into CommemorationModifiers
	(CommemorationType,					                  ModifierId)
select
  'COMMEMORATION_HD_RELIGIOUS_WAR',             'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_SCIENCE'
from Improvements where PlunderType != 'NO_PLUNDER';

insert or replace into CommemorationModifiers
	(CommemorationType,					                  ModifierId)
select
  'COMMEMORATION_HD_RELIGIOUS_WAR',             'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_CULTURE'
from Improvements where PlunderType != 'NO_PLUNDER';

  -- 开明专制
insert or replace into CommemorationModifiers
	(CommemorationType,					                  ModifierId)
select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',     'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS'
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into CommemorationModifiers
	(CommemorationType,					                  ModifierId)
select
	'COMMEMORATION_HD_ROMANTICISM',			          'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER'
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or replace into Modifiers
	(ModifierId,								                                            ModifierType,											                                  OwnerRequirementSetId,		  SubjectRequirementSetId)
values
  -- 自由探索(自然哲学)
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_COMMEMORATION_SCIENTIFIC_DISTRICT_REQUIREMENTS'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_COMMEMORATION_SCIENTIFIC_DISTRICT_REQUIREMENTS'),
  -- 百花齐放(轴心时代)
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_DISTRICTS_IS_NOT_WONDERS_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_DISTRICTS_IS_NOT_WONDERS_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS',                 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',                        'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_SPECIALTY_DISTRICT_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'MODIFIER_PLAYER_DISTRICT_ADJUST_GREAT_PERSON_POINTS',              Null,                       Null),
  -- 雄伟壮丽
  -- ('COMMEMORATION_INFRASTRUCTURE_DISTRICT_PRODUCTION',                    'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION',           'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT',                         'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',                            'PLAYER_HAS_GOLDEN_AGE',    'BUILDING_IS_PALACE'),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_ERA_PRODUCTION',              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'DL_CITY_HAS_WONDER_REQUIREMENTS'),
  -- 布道者的远行(光荣胜利)
  ('COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT',                            'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_RELIGIOUS_UNIT_STRENGTH',                               'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'MODIFIER_PLAYER_ADJUST_GOLD_DISPERSAL',                            'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS',              'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST',                          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS',             'MODIFIER_PLAYER_ADJUST_CIVIC_BOOST',                               'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_INDUSTRIAL_ZONE'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_COMMERCIAL_HUB'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_HARBOR'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED',                     'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT',                     'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_BY_NUMBER_RESOURCES',          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_BY_NUMBER_RESOURCES',          'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED',                       'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT',           'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_PILLAGE',                       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT',              'MODIFIER_PLAYER_ADJUST_DISTRICT_PILLAGE',                          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED',                      'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE',                     'MODIFIER_PLAYER_UNITS_RELIGIOUS_SPREADS',                          'PLAYER_HAS_GOLDEN_AGE',    'UNIT_IS_RELIGIOUS'),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT',		                  'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT',		            'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',		                        'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 工商业本位
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',                         'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',                         'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING',		                    'MODIFIER_PLAYER_CITIES_ADJUST_ALL_BUILDINGS_PURCHASE_COST',	      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT',		                    'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PURCHASE_COST',	      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'MODIFIER_PLAYER_CITIES_ADJUST_UNITS_PURCHASE_COST',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',		          'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		            'PLAYER_HAS_GOLDEN_AGE',	  'HD_CITY_HAS_RELIGIOUS_TIER_3_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',		                'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		              'PLAYER_HAS_GOLDEN_AGE',	  'DISTRICT_IS_HOLY_SITE'),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION_CIVILIAN_SPEED',		                        'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',						                  'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION',	                      'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION',	          'PLAYER_HAS_GOLDEN_AGE',	  'CITY_HAS_0_SPECIALTY_DISTRICTS_REQUIREMENTS'),
  -- 蒸汽滚滚
  ('COMMEMORATION_INUDSTRIAL_INDUSTRIAL_ZONE_BONUS',		                  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',	'PLAYER_HAS_GOLDEN_AGE',	  'DISTRICT_IS_INDUSTRIAL_ZONE'),
	('COMMEMORATION_INUDSTRIAL_CAMPUS_BONUS',	                              'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',  'PLAYER_HAS_GOLDEN_AGE',	  'DISTRICT_IS_CAMPUS'),
  -- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',	              'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS',	            'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST',                          'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',	    'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 全民皆兵
	('COMMEMORATION_MILITARY_STRENGTH',	                                    'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 愿你在此
	('COMMEMORATION_TOURISM_IMPROVEMENT',	                                  'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',                'PLAYER_HAS_GOLDEN_AGE',	  Null);

update Modifiers set ModifierType = 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', NewOnly = 1, Permanent = 1 where ModifierId = 'COMMEMORATION_EXPLORATION_GA_NEW_CITY_POPULATION';
update Modifiers set OwnerRequirementSetId = 'PLAYER_HAS_GOLDEN_AGE', SubjectRequirementSetId = Null where ModifierId = 'COMMEMORATION_TOURISM_GA_WONDERS';
update Modifiers set Permanent = 1 where ModifierId in ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT', 'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE');

  -- 信仰之战
insert or replace into Modifiers
	(ModifierId,								                                                ModifierType,											             OwnerRequirementSetId)
select
  'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_SCIENCE', 'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING', 'PLAYER_HAS_GOLDEN_AGE'
from Improvements where PlunderType != 'NO_PLUNDER';

insert or replace into Modifiers
	(ModifierId,								                                                ModifierType,											             OwnerRequirementSetId)
select
  'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_CULTURE', 'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING', 'PLAYER_HAS_GOLDEN_AGE'
from Improvements where PlunderType != 'NO_PLUNDER';

  -- 开明专制
insert or replace into Modifiers
	(ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId)
select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',
  'PLAYER_HAS_GOLDEN_AGE',
  'HD_IS_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into Modifiers
	(ModifierId,																														          ModifierType,                             OwnerRequirementSetId)
select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',  'PLAYER_HAS_GOLDEN_AGE'
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or replace into ModifierArguments
	(ModifierId,								                                            Name,						          Value)
values
  -- 自由探索(自然哲学)
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'Amount',                 1),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'Amount',                 1),
  -- 自由探索(自然哲学)
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'YieldType',              'YIELD_FAITH'),
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'Amount',                 1),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'Amount',                 1),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS',                 'ModifierId',             'COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'GreatPersonClassType',   'GREAT_PERSON_CLASS_WRITER'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'Amount',                 3),
  -- 雄伟壮丽
  -- ('COMMEMORATION_INFRASTRUCTURE_DISTRICT_PRODUCTION',                    'Amount',                 15),
  ('COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT',                         'Amount',                 1),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'Amount',                 15),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'IsWonder',               1),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'StartEra',               'ERA_ANCIENT'),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'EndEra',                 'ERA_MEDIEVAL'),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'YieldType',              'YIELD_FOOD,YIELD_PRODUCTION'),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'Amount',                 '10,10'),
  -- 布道者的远行(光荣胜利)
  ('COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT',                            'AbilityType',            'ABILITY_COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT'),
  ('COMMEMORATION_RELIGIOUS_UNIT_STRENGTH',                               'AbilityType',            'ABILITY_COMMEMORATION_RELIGIOUS_UNIT_STRENGTH'),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'Amount',                 50),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'Improvement',            'IMPROVEMENT_BARBARIAN_CAMP'),
  -- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'DistrictType',           'DISTRICT_CAMPUS'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'DistrictType',           'DISTRICT_CAMPUS'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'DistrictType',           'DISTRICT_THEATER'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'DistrictType',           'DISTRICT_THEATER'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS',              'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'Key',                    'HD_Player_Extra_Tech_Boost'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS',             'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'Key',                    'HD_Player_Extra_Civic_Boost'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'Amount',                 3),
  -- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'Amount',                 6),
  -- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED',                     'AbilityType',            'ABILITY_COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'UnitType',               'UNIT_BUILDER'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'Amount',                 1),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'YieldType',              'YIELD_FOOD'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'Amount',                 1),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'Amount',                 1),
  -- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED',                       'AbilityType',            'ABILITY_COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED'),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT',           'Amount',                 50),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT',              'Amount',                 50),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED',                      'AbilityType',            'ABILITY_COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED'),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE',                     'Amount',                 2),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT',		                  'GovernmentSlotType',	    'SLOT_WILDCARD'),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT',		            'Amount',	                1),
  -- 工商业本位
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'GreatPersonClassType',	  'GREAT_PERSON_CLASS_MERCHANT'),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'Amount',	                50),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'GreatPersonClassType',	  'GREAT_PERSON_CLASS_ENGINEER'),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'Amount',	                50),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'YieldType',	            'YIELD_GOLD'),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'Amount',	                6),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'YieldType',	            'YIELD_PRODUCTION'),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'Amount',	                2),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING',		                    'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT',		                    'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'IncludeCivilian',	      1),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',             'YieldType',              'YIELD_SCIENCE,YIELD_CULTURE,YIELD_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',             'Amount',                 '10,10,10'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',                   'YieldType',	            'YIELD_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',                   'Amount',	                100),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION_CIVILIAN_SPEED',			                      'AbilityType',		        'ABILITY_COMMEMORATION_EXPLORATION_CIVILIAN_SPEED'),
	('COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION',		                    'Amount',		              100),
  -- 蒸汽滚滚
	('COMMEMORATION_INUDSTRIAL_INDUSTRIAL_ZONE_BONUS',	                    'YieldTypeToMirror',	    'YIELD_PRODUCTION'),
	('COMMEMORATION_INUDSTRIAL_INDUSTRIAL_ZONE_BONUS',	                    'YieldTypeToGrant',		    'YIELD_SCIENCE'),
	('COMMEMORATION_INUDSTRIAL_CAMPUS_BONUS',	                              'YieldTypeToMirror',	    'YIELD_SCIENCE'),
	('COMMEMORATION_INUDSTRIAL_CAMPUS_BONUS',	                              'YieldTypeToGrant',		    'YIELD_PRODUCTION'),
  -- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'GreatPersonClassType',	  'GREAT_PERSON_CLASS_WRITER'),
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'Amount',	                50),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'GreatPersonClassType',	  'GREAT_PERSON_CLASS_ARTIST'),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'Amount',	                50),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'GreatPersonClassType',	  'GREAT_PERSON_CLASS_MUSICIAN'),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'Amount',	                50),
  -- 科学革命
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'GreatPersonClassType',	  'GREAT_PERSON_CLASS_SCIENTIST'),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'Amount',	                50),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS',		          'Amount',	                7),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',      'Key',	                  'HD_Player_Extra_Tech_Boost'),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',      'Amount',	                7),
  -- 全民皆兵
  ('COMMEMORATION_MILITARY_STRENGTH',		                                  'AbilityType',	          'ABILITY_COMMEMORATION_MILITARY_STRENGTH'),
  -- 愿你在此
  ('COMMEMORATION_TOURISM_IMPROVEMENT',		                                'Amount',	                300);

update ModifierArguments set Value = 25 where ModifierId = 'COMMEMORATION_INDUSTRIAL_GA_INDUSTRIALINFORMATION' and Name = 'Amount';
update ModifierArguments set Value = 100 where ModifierId = 'COMMEMORATION_MILITARY_GA_PRODUCTION' and Name = 'Amount';
update ModifierArguments set Value = 400 where ModifierId = 'COMMEMORATION_TOURISM_GA_WONDERS' and Name = 'ScalingFactor';
update ModifierArguments set Value = 300 where ModifierId = 'COMMEMORATION_TOURISM_GA_NATIONAL_PARKS' and Name = 'Amount';

  -- 开明专制
insert or replace into ModifierArguments
	(ModifierId, Name, Value)
select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'YieldType', a.YieldType
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

insert or replace into ModifierArguments
	(ModifierId, Name, Value)
select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'Amount', 50
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into ModifierArguments
	(ModifierId,																														          Name,										Value)
select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'ScalingFactor',				400
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or replace into ModifierArguments
	(ModifierId,																														          Name,										Value)
select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'GreatWorkObjectType',	GreatWorkObjectType
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

-- 全局参数 用于Lua
insert or replace into GlobalParameters
  (Name,                                                           Value)
values
  -- 自由探索(自然哲学)
  ('HD_COMMEMORATION_SCIENTIFIC_SCIENTIST_POINTS',                 10),
  -- 布道者的远行(光荣胜利)
  ('HD_COMMEMORATION_RELIGIOUS_CONQUER_CITY_GOODY_HUT',            1),
  ('HD_COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_ERA_SCORE',          1),
  ('HD_COMMEMORATION_RELIGIOUS_CONQUER_CITY_ERA_SCORE',            3),
  -- 翻译运动
  ('HD_COMMEMORATION_HD_TRANSLATION_MOVEMENT_GP_ERA_SCORE',        1),
  -- 筚路蓝缕
  ('HD_COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_ERA_SCORE',      1),
  -- 开明专制
  ('HD_COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_DISTRICT_ERA_SCORE', 2),
  -- 工商业本位
  ('HD_COMMEMORATION_ECONOMIC_GP_ERA_SCORE',                       2),
  -- 宗教改革
  ('HD_COMMEMORATION_HD_RELIGIOUS_REFORM_DISTRICT_ERA_SCORE',      2),
  -- 浪漫主义
  ('HD_COMMEMORATION_HD_ROMANTICISM_GW_ERA_SCORE',                 1),
  -- 科技革命
  ('HD_COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_ERA_SCORE',     1),
  -- AI保底时代分
  ('HD_AI_TURN_END_ERA_SCORE',                                     1),
  ('HD_AI_DISTRICT_ERA_SCORE',                                     1);

-------------------------------------
-- 历史时刻
update Moments set MinimumGameEra = Null, MaximumGameEra = Null where MomentType in (
  'MOMENT_BARBARIAN_CAMP_DESTROYED',
  'MOMENT_BARBARIAN_CAMP_DESTROYED_NEAR_YOUR_CITY',
  'MOMENT_GOODY_HUT_TRIGGERED'
);
update Moments set EraScore = 4 where MomentType in (
  'MOMENT_NATIONAL_PARK_CREATED',
  'MOMENT_GREAT_PERSON_CREATED_PATRONAGE_FAITH_OVER_HALF',
  'MOMENT_GREAT_PERSON_CREATED_PATRONAGE_GOLD_OVER_HALF',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_RENEWABLE_ENERGY_FIRST_IN_WORLD',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_MOUNTAIN_TUNNEL_FIRST_IN_WORLD',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_SEASIDE_RESORT_FIRST_IN_WORLD',
  'MOMENT_FIRST_CORPORATION_IN_WORLD',
  'MOMENT_FIND_NATURAL_WONDER_FIRST_IN_WORLD',
  'MOMENT_ARTIFACT_EXTRACTED_SHIPWRECK_FIRST_IN_WORLD',
  'MOMENT_ROUTE_CREATED_RAILROAD_CONNECTS_TWO_CITIES_FIRST_IN_WORLD'
);
update Moments set EraScore = 3 where MomentType in (
  'MOMENT_FIND_NATURAL_WONDER'
);