insert or ignore into Types (Type, Kind) values
  -- 布达拉宫
  ('NOTIFICATION_POTALA_EXTRA_BELIEF', 'KIND_NOTIFICATION'),
  -- 中国远古着力点
  ('NOTIFICATION_CHINA_CHOOSE_FIRST_TURN_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ANCIENT_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_CLASSICAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MEDIEVAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_RENAISSANCE_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INDUSTRIAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MODERN_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ATOMIC_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INFORMATION_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_FUTURE_COMMEMORATION', 'KIND_NOTIFICATION'),
  -- 苏美尔
  ('NOTIFICATION_SUMERIA_FREE_TECH', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_FREE_CIVIC', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST_REWORD', 'KIND_NOTIFICATION'),
  -- 波兰
  ('NOTIFICATION_POLAND_ALLIANCE_COPY_GPP', 'KIND_NOTIFICATION'),
  -- 梅花内卫
  ('NOTIFICATION_PLUM_INTERNAL_SECURITY_GPP', 'KIND_NOTIFICATION');

insert or ignore into Notifications
  (NotificationType,                                          SeverityType,	ExpiresEndOfTurn,	AutoNotify, AutoActivate)
values
  -- 布达拉宫
  ('NOTIFICATION_POTALA_EXTRA_BELIEF',	                      'MID',			  0,					      0,			    0),
  -- 中国远古着力点
  ('NOTIFICATION_CHINA_CHOOSE_FIRST_TURN_COMMEMORATION',	    'MID',			  0,					      0,			    1),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ANCIENT_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_CLASSICAL_COMMEMORATION',	  'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MEDIEVAL_COMMEMORATION',	  'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_RENAISSANCE_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INDUSTRIAL_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MODERN_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ATOMIC_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INFORMATION_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_FUTURE_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  -- 苏美尔
  ('NOTIFICATION_SUMERIA_FREE_TECH',	                        'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_FREE_CIVIC',	                        'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST',	                    'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST_REWORD',	              'MID',			  1,					      0,			    0),
  -- 波兰
  ('NOTIFICATION_POLAND_ALLIANCE_COPY_GPP',	                  'MID',			  1,					      0,			    0),
  -- 梅花内卫
  ('NOTIFICATION_PLUM_INTERNAL_SECURITY_GPP',	                'MID',			  1,					      0,			    0);