insert or ignore into HD_CityState_Resources (CityStateType, ResourceType, ResourceClassificationType) values
  -- 科技
  ('SCIENTIFIC',        'RESOURCE_HD_CS_MANUSCRIPT',            'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('SCIENTIFIC',        'RESOURCE_HD_CS_MEDICINAL_HERBS',       'RESOURCE_CLASSIFICATION_HD_MEDICINE'),
  ('SCIENTIFIC',        'RESOURCE_HD_CS_DIDACTIC_MATERIALS',    'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('SCIENTIFIC',        'RESOURCE_HD_CS_ASTROLABE',             'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  -- 文化
  ('CULTURAL',          'RESOURCE_HD_CS_DANCE_COSTUME',         'RESOURCE_CLASSIFICATION_HD_CLOTH'),
  ('CULTURAL',          'RESOURCE_HD_CS_MUSICAL_INSTRUMENTS',   'RESOURCE_CLASSIFICATION_HD_ART'),
  ('CULTURAL',          'RESOURCE_HD_CS_FLOWER_ARRANGEMENT',    'RESOURCE_CLASSIFICATION_HD_ORNAMENTAL'),
  ('CULTURAL',          'RESOURCE_HD_CS_TEA_SET',               'RESOURCE_CLASSIFICATION_HD_HOUSEHOLD'),
  -- 贸易
  ('TRADE',             'RESOURCE_HD_CS_CARAVAN',               'RESOURCE_CLASSIFICATION_HD_TRANSIT'),
  ('TRADE',             'RESOURCE_HD_CS_STRUCK_COINAGE',        'RESOURCE_CLASSIFICATION_HD_MINTING'),
  ('TRADE',             'RESOURCE_HD_CS_EXOTIC_BEAST',          'RESOURCE_CLASSIFICATION_HD_BEAST'),
  ('TRADE',             'RESOURCE_HD_CS_RARE_BIRD',             'RESOURCE_CLASSIFICATION_HD_BEAST'),
  -- 军事
  ('MILITARISTIC',      'RESOURCE_HD_CS_CANOPIED_CART',         'RESOURCE_CLASSIFICATION_HD_TRANSIT'),
  ('MILITARISTIC',      'RESOURCE_HD_CS_MASTERWORK_SWORD',      'RESOURCE_CLASSIFICATION_HD_DECORATION'),
  ('MILITARISTIC',      'RESOURCE_HD_CS_DESTRIER',              'RESOURCE_CLASSIFICATION_HD_TRANSIT'),
  ('MILITARISTIC',      'RESOURCE_HD_CS_ARMOR',                 'RESOURCE_CLASSIFICATION_HD_CLOTH'),
  -- 宗教
  ('RELIGIOUS',         'RESOURCE_HD_CS_DEITY_STATUE',          'RESOURCE_CLASSIFICATION_HD_ART'),
  ('RELIGIOUS',         'RESOURCE_HD_CS_ROSARY',                'RESOURCE_CLASSIFICATION_HD_DECORATION'),
  ('RELIGIOUS',         'RESOURCE_HD_CS_SCRIPTURE',             'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('RELIGIOUS',         'RESOURCE_HD_CS_ORACLE_IMPLEMENTS',     'RESOURCE_CLASSIFICATION_HD_CELEBRATION'),
  -- 农业
  ('CSE_AGRICULTURAL',  'RESOURCE_HD_CS_ALMANAC',               'RESOURCE_CLASSIFICATION_HD_AGRICULTURE'),
  ('CSE_AGRICULTURAL',  'RESOURCE_HD_CS_YEAST',                 'RESOURCE_CLASSIFICATION_HD_BREWING'),
  ('CSE_AGRICULTURAL',  'RESOURCE_HD_CS_RESIN',                 'RESOURCE_CLASSIFICATION_HD_CHEMISTRY'),
  ('CSE_AGRICULTURAL',  'RESOURCE_HD_CS_CASK',                  'RESOURCE_CLASSIFICATION_HD_BREWING'),
  -- 海洋
  ('CSE_MARITIME',      'RESOURCE_HD_CS_SEA_CHART',             'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('CSE_MARITIME',      'RESOURCE_HD_CS_FIGUREHEAD',            'RESOURCE_CLASSIFICATION_HD_DECORATION'),
  ('CSE_MARITIME',      'RESOURCE_HD_CS_CANVAS',                'RESOURCE_CLASSIFICATION_HD_CLOTH'),
  ('CSE_MARITIME',      'RESOURCE_HD_CS_YACHT',                 'RESOURCE_CLASSIFICATION_HD_TRANSIT'),
  -- 工业
  ('INDUSTRIAL',        'RESOURCE_HD_CS_TERRACOTTA',            'RESOURCE_CLASSIFICATION_HD_CONSTRUCTION'),
  ('INDUSTRIAL',        'RESOURCE_HD_CS_MEASURING_INSTRUMENT',  'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('INDUSTRIAL',        'RESOURCE_HD_CS_RED_BRICK',             'RESOURCE_CLASSIFICATION_HD_CONSTRUCTION'),
  ('INDUSTRIAL',        'RESOURCE_HD_CS_STEEL',                 'RESOURCE_CLASSIFICATION_HD_METALLURGY'),
  -- 轻工业
  ('LIGHT_INDUSTRIAL',  'RESOURCE_HD_CS_TIMEPIECE',             'RESOURCE_CLASSIFICATION_HD_STATIONERY'),
  ('LIGHT_INDUSTRIAL',  'RESOURCE_HD_CS_SEWING_MACHINE',        'RESOURCE_CLASSIFICATION_HD_CLOTH'),
  ('LIGHT_INDUSTRIAL',  'RESOURCE_HD_CS_CANDLE',                'RESOURCE_CLASSIFICATION_HD_HOUSEHOLD'),
  ('LIGHT_INDUSTRIAL',  'RESOURCE_HD_CS_WHITE_PAPER',           'RESOURCE_CLASSIFICATION_HD_STATIONERY');

insert or ignore into Types (Type, Kind) select
  ResourceType, 'KIND_RESOURCE'
from HD_CityState_Resources;

insert or ignore into Resources (ResourceType, Name, ResourceClassType, Happiness) select
	ResourceType, 'LOC_' || ResourceType || '_NAME', 'RESOURCECLASS_LUXURY', 4
from HD_CityState_Resources;