---- 保护区新建筑
insert or ignore into Types
	(Type,								                    Kind)
values
	('BUILDING_HD_MONASTERY',			            'KIND_BUILDING'),
	('BUILDING_HD_HOLYWATERS',			          'KIND_BUILDING'),

	('BUILDING_HD_JUNGLE_PRESERVE',		        'KIND_BUILDING'),
	('BUILDING_HD_WETLANDS_PRESERVE',	        'KIND_BUILDING'),
	('BUILDING_HD_WATER_PRESERVE',		        'KIND_BUILDING'),

  ('BUILDING_HD_CULTURE_HERITAGE_PRESERVE',	'KIND_BUILDING'),

	('BUILDING_HD_LANDFORM_EPO',		          'KIND_BUILDING'),
	('BUILDING_HD_RESOURCE_EPO',		          'KIND_BUILDING'),
	('BUILDING_HD_SPECIES_EPO',		            'KIND_BUILDING'),
	('BUILDING_HD_SCENIC_EPO',		            'KIND_BUILDING'),

  ('BUILDING_HD_DUMMY_PREREQ_PRESERVE',		  'KIND_BUILDING'),
	('BUILDING_HD_DUMMY_FOREST_PRESERVE',		  'KIND_BUILDING'),
	('BUILDING_HD_DUMMY_JUNGLE_PRESERVE',		  'KIND_BUILDING'),
	('BUILDING_HD_DUMMY_WETLANDS_PRESERVE',   'KIND_BUILDING'),
	('BUILDING_HD_DUMMY_WATER_PRESERVE',		  'KIND_BUILDING'),
	('BUILDING_HD_DUMMY_HERITAGE_PRESERVE',		'KIND_BUILDING');

insert or ignore into Buildings
	(BuildingType,			                      PrereqDistrict,				    PrereqCivic,		      PrereqTech, 	      Cost,	Maintenance,	PurchaseYield,	AdvisorType,			    Name,								                              Description)
values					
  ('BUILDING_HD_MONASTERY',	                'DISTRICT_PRESERVE',	    NULL,	                'TECH_ASTROLOGY',   75,		1,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_MONASTERY_NAME',		              'LOC_BUILDING_HD_MONASTERY_DESCRIPTION'),
	('BUILDING_HD_HOLYWATERS',		            'DISTRICT_PRESERVE',	    'CIVIC_MYSTICISM',	  NULL,       	      75,		1,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_HOLYWATERS_NAME',			          'LOC_BUILDING_HD_HOLYWATERS_DESCRIPTION'),

	('BUILDING_HD_JUNGLE_PRESERVE',		        'DISTRICT_PRESERVE',	    'CIVIC_GUILDS',	      NULL,       	      150,	4,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_JUNGLE_PRESERVE_NAME',		        'LOC_BUILDING_HD_JUNGLE_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_WETLANDS_PRESERVE',         'DISTRICT_PRESERVE',	    NULL,	                'TECH_BUTTRESS',    150,	4,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_WETLANDS_PRESERVE_NAME',	        'LOC_BUILDING_HD_WETLANDS_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_WATER_PRESERVE',		        'DISTRICT_PRESERVE',	    NULL,	                'TECH_COMPASS_HD',  150,	4,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_WATER_PRESERVE_NAME',		        'LOC_BUILDING_HD_WATER_PRESERVE_DESCRIPTION'),
	
  ('BUILDING_HD_CULTURE_HERITAGE_PRESERVE',	'DISTRICT_PRESERVE',	    'CIVIC_HUMANISM',	    NULL,               240,	4,				    'YIELD_GOLD',		'ADVISOR_GENERIC',		'LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_NAME',	'LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_DESCRIPTION'),

	('BUILDING_HD_LANDFORM_EPO',		          'DISTRICT_PRESERVE',	    'CIVIC_CONSERVATION',	NULL,       	      750,	7,				    NULL,				    'ADVISOR_GENERIC',		'LOC_BUILDING_HD_LANDFORM_EPO_NAME',		          'LOC_BUILDING_HD_LANDFORM_EPO_DESCRIPTION'),
	('BUILDING_HD_RESOURCE_EPO',		          'DISTRICT_PRESERVE',	    NULL,	                'TECH_CHEMISTRY',   750,	7,				    NULL,				    'ADVISOR_GENERIC',		'LOC_BUILDING_HD_RESOURCE_EPO_NAME',		          'LOC_BUILDING_HD_RESOURCE_EPO_DESCRIPTION'),
	('BUILDING_HD_SPECIES_EPO',		            'DISTRICT_PRESERVE',	    NULL,	                'TECH_BIOLOGY_HD',  750,	7,				    NULL,				    'ADVISOR_GENERIC',		'LOC_BUILDING_HD_SPECIES_EPO_NAME',			          'LOC_BUILDING_HD_SPECIES_EPO_DESCRIPTION'),
	('BUILDING_HD_SCENIC_EPO',		            'DISTRICT_PRESERVE',	    'CIVIC_CONSERVATION',	NULL,       	      750,	7,				    NULL,				    'ADVISOR_GENERIC',		'LOC_BUILDING_HD_SCENIC_EPO_NAME',			          'LOC_BUILDING_HD_SCENIC_EPO_DESCRIPTION'),
	
  ('BUILDING_HD_DUMMY_PREREQ_PRESERVE',		  'DISTRICT_CITY_CENTER',	  NULL,	                NULL,       	      1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_PREREQ_PRESERVE_NAME',		  'LOC_BUILDING_HD_DUMMY_PREREQ_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_DUMMY_FOREST_PRESERVE',		  NULL,	                    NULL,	                NULL,               1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_FOREST_PRESERVE_NAME',		  'LOC_BUILDING_HD_DUMMY_FOREST_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_DUMMY_JUNGLE_PRESERVE',		  NULL,	                    NULL,	                NULL,               1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_JUNGLE_PRESERVE_NAME',		  'LOC_BUILDING_HD_DUMMY_JUNGLE_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_DUMMY_WETLANDS_PRESERVE',		NULL,	                    NULL,	                NULL,       	      1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_WETLANDS_PRESERVE_NAME',		'LOC_BUILDING_HD_DUMMY_WETLANDS_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_DUMMY_WATER_PRESERVE',		  NULL,	                    NULL,	                NULL,       	      1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_WATER_PRESERVE_NAME',		  'LOC_BUILDING_HD_DUMMY_WATER_PRESERVE_DESCRIPTION'),
	('BUILDING_HD_DUMMY_HERITAGE_PRESERVE',		NULL,	                    NULL,	                NULL,       	      1,	  0,				    NULL,		        'ADVISOR_GENERIC',		'LOC_BUILDING_HD_DUMMY_HERITAGE_PRESERVE_NAME',		'LOC_BUILDING_HD_DUMMY_HERITAGE_PRESERVE_DESCRIPTION');

update Buildings set InternalOnly = 1 where BuildingType = 'BUILDING_HD_DUMMY_PREREQ_PRESERVE';
update Buildings set MaxPlayerInstances = 1 where BuildingType in ('BUILDING_HD_LANDFORM_EPO','BUILDING_HD_RESOURCE_EPO','BUILDING_HD_SPECIES_EPO','BUILDING_HD_SCENIC_EPO');
update Buildings set Maintenance = 1,	Cost = 75, AdvisorType = 'ADVISOR_GENERIC', PrereqCivic = NULL, PrereqTech = 'TECH_ARCHERY' where BuildingType = 'BUILDING_GROVE';
update Buildings set Maintenance = 4,	Cost = 150, AdvisorType = 'ADVISOR_GENERIC', PrereqCivic = NULL, PrereqTech = 'TECH_ARCH_HD' where BuildingType = 'BUILDING_SANCTUARY';

insert or replace into Building_YieldChanges
	(BuildingType,					    YieldType,			YieldChange)
values
	('BUILDING_GROVE',				  'YIELD_CULTURE',	1),
	('BUILDING_HD_MONASTERY',		'YIELD_FAITH',		2),
	('BUILDING_HD_HOLYWATERS',	'YIELD_SCIENCE',	1);

insert or ignore into Buildings_XP2
  (BuildingType,                              Pillage)
values
  ('BUILDING_HD_DUMMY_PREREQ_PRESERVE',       0),
  ('BUILDING_HD_DUMMY_FOREST_PRESERVE',       0),
  ('BUILDING_HD_DUMMY_JUNGLE_PRESERVE',       0),
  ('BUILDING_HD_DUMMY_WETLANDS_PRESERVE',     0),
  ('BUILDING_HD_DUMMY_WATER_PRESERVE',        0),
  ('BUILDING_HD_DUMMY_HERITAGE_PRESERVE',     0);

insert or replace into HD_DUMMY_BUILDINGS (BuildingType) values
  ('BUILDING_HD_DUMMY_PREREQ_PRESERVE'),
  ('BUILDING_HD_DUMMY_FOREST_PRESERVE'),
  ('BUILDING_HD_DUMMY_JUNGLE_PRESERVE'),
  ('BUILDING_HD_DUMMY_WETLANDS_PRESERVE'),
  ('BUILDING_HD_DUMMY_WATER_PRESERVE'),
  ('BUILDING_HD_DUMMY_HERITAGE_PRESERVE');

insert or ignore into MutuallyExclusiveBuildings
	(Building,							          MutuallyExclusiveBuilding)
values
	('BUILDING_GROVE',				        'BUILDING_HD_MONASTERY'),
	('BUILDING_GROVE',					      'BUILDING_HD_HOLYWATERS'),
  ('BUILDING_HD_MONASTERY',			    'BUILDING_GROVE'),
	('BUILDING_HD_MONASTERY',		      'BUILDING_HD_HOLYWATERS'),
  ('BUILDING_HD_HOLYWATERS',			  'BUILDING_HD_MONASTERY'),
	('BUILDING_HD_HOLYWATERS',		    'BUILDING_GROVE'),

  ('BUILDING_SANCTUARY',			      'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_SANCTUARY',			      'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_SANCTUARY',			      'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_JUNGLE_PRESERVE',   'BUILDING_SANCTUARY'),
  ('BUILDING_HD_JUNGLE_PRESERVE',   'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_HD_JUNGLE_PRESERVE',   'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_WETLANDS_PRESERVE', 'BUILDING_SANCTUARY'),
  ('BUILDING_HD_WETLANDS_PRESERVE', 'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_WETLANDS_PRESERVE', 'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_WATER_PRESERVE',	  'BUILDING_SANCTUARY'),
  ('BUILDING_HD_WATER_PRESERVE',	  'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_WATER_PRESERVE',	  'BUILDING_HD_WETLANDS_PRESERVE'),

  ('BUILDING_HD_LANDFORM_EPO',      'BUILDING_HD_RESOURCE_EPO'),
  ('BUILDING_HD_LANDFORM_EPO',      'BUILDING_HD_SPECIES_EPO'),
  ('BUILDING_HD_LANDFORM_EPO',      'BUILDING_HD_SCENIC_EPO'),
  ('BUILDING_HD_RESOURCE_EPO',      'BUILDING_HD_LANDFORM_EPO'),
  ('BUILDING_HD_RESOURCE_EPO',      'BUILDING_HD_SPECIES_EPO'),
  ('BUILDING_HD_RESOURCE_EPO',      'BUILDING_HD_SCENIC_EPO'),
  ('BUILDING_HD_SPECIES_EPO',	      'BUILDING_HD_LANDFORM_EPO'),
  ('BUILDING_HD_SPECIES_EPO',	      'BUILDING_HD_RESOURCE_EPO'),
  ('BUILDING_HD_SPECIES_EPO',	      'BUILDING_HD_SCENIC_EPO'),
  ('BUILDING_HD_SCENIC_EPO',	      'BUILDING_HD_LANDFORM_EPO'),
  ('BUILDING_HD_SCENIC_EPO',	      'BUILDING_HD_RESOURCE_EPO'),
  ('BUILDING_HD_SCENIC_EPO',	      'BUILDING_HD_SPECIES_EPO');

insert or ignore into BuildingPrereqs
	(Building,							                    PrereqBuilding)
values
  ('BUILDING_HD_DUMMY_FOREST_PRESERVE',       'BUILDING_HD_DUMMY_PREREQ_PRESERVE'),
  ('BUILDING_HD_DUMMY_JUNGLE_PRESERVE',       'BUILDING_HD_DUMMY_PREREQ_PRESERVE'),
  ('BUILDING_HD_DUMMY_WETLANDS_PRESERVE',     'BUILDING_HD_DUMMY_PREREQ_PRESERVE'),
  ('BUILDING_HD_DUMMY_WATER_PRESERVE',        'BUILDING_HD_DUMMY_PREREQ_PRESERVE'),
  ('BUILDING_HD_DUMMY_HERITAGE_PRESERVE',     'BUILDING_HD_DUMMY_PREREQ_PRESERVE'),

	('BUILDING_SANCTUARY',  			              'BUILDING_HD_DUMMY_FOREST_PRESERVE'),
  ('BUILDING_HD_JUNGLE_PRESERVE',		          'BUILDING_HD_DUMMY_JUNGLE_PRESERVE'),
  ('BUILDING_HD_WETLANDS_PRESERVE',	          'BUILDING_HD_DUMMY_WETLANDS_PRESERVE'),
  ('BUILDING_HD_WATER_PRESERVE',		          'BUILDING_HD_DUMMY_WATER_PRESERVE'),
  ('BUILDING_HD_CULTURE_HERITAGE_PRESERVE',	  'BUILDING_HD_DUMMY_HERITAGE_PRESERVE'),

  ('BUILDING_HD_LANDFORM_EPO',		            'BUILDING_SANCTUARY'),
	('BUILDING_HD_LANDFORM_EPO',		            'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_LANDFORM_EPO',		            'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_HD_LANDFORM_EPO',		            'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_LANDFORM_EPO',		            'BUILDING_HD_CULTURE_HERITAGE_PRESERVE'),

  ('BUILDING_HD_RESOURCE_EPO',		            'BUILDING_SANCTUARY'),
	('BUILDING_HD_RESOURCE_EPO',		            'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_RESOURCE_EPO',		            'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_HD_RESOURCE_EPO',		            'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_RESOURCE_EPO',		            'BUILDING_HD_CULTURE_HERITAGE_PRESERVE'),

  ('BUILDING_HD_SPECIES_EPO',		              'BUILDING_SANCTUARY'),
	('BUILDING_HD_SPECIES_EPO',		              'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_SPECIES_EPO',		              'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_HD_SPECIES_EPO',		              'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_SPECIES_EPO',		              'BUILDING_HD_CULTURE_HERITAGE_PRESERVE'),

  ('BUILDING_HD_SCENIC_EPO',		              'BUILDING_SANCTUARY'),
	('BUILDING_HD_SCENIC_EPO',		              'BUILDING_HD_JUNGLE_PRESERVE'),
  ('BUILDING_HD_SCENIC_EPO',		              'BUILDING_HD_WETLANDS_PRESERVE'),
  ('BUILDING_HD_SCENIC_EPO',		              'BUILDING_HD_WATER_PRESERVE'),
  ('BUILDING_HD_SCENIC_EPO',		              'BUILDING_HD_CULTURE_HERITAGE_PRESERVE');