insert or ignore into IconTextureAtlases (Name, IconSize, IconsPerRow, IconsPerColumn, Filename) values
  ('ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 256, 4, 4, 'HD_SCOTLAND_SELECTIONS_256.dds');

insert or replace into IconDefinitions (Name, Atlas, 'Index') values
  ('ICON_HD_SELECTION_GOODY_HUT_RECON',     'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 0),
  ('ICON_HD_SELECTION_GOODY_HUT_LAND',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 1),
  ('ICON_HD_SELECTION_GOODY_HUT_CAVALRY',   'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 2),
  ('ICON_HD_SELECTION_GOODY_HUT_NAVAL',     'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 3),
  ('ICON_HD_SELECTION_GOODY_HUT_SAPPER',    'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 4),
  ('ICON_HD_SELECTION_GOODY_HUT_GOLD',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 5),
  ('ICON_HD_SELECTION_GOODY_HUT_LUXURY',    'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 6),
  ('ICON_HD_SELECTION_GOODY_HUT_STRATEGIC', 'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 7),
  ('ICON_HD_SELECTION_GOODY_HUT_HEAL',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 8),
  ('ICON_HD_SELECTION_GOODY_HUT_PROMOTION', 'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 9),
  ('ICON_HD_SELECTION_GOODY_HUT_MOVEMENT',  'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 10),
  ('ICON_HD_SELECTION_GOODY_HUT_BUILDER',   'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 11),

  ('ICON_HD_SELECTION_BARBARIAN_RECON',     'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 0),
  ('ICON_HD_SELECTION_BARBARIAN_LAND',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 1),
  ('ICON_HD_SELECTION_BARBARIAN_CAVALRY',   'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 2),
  ('ICON_HD_SELECTION_BARBARIAN_NAVAL',     'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 3),
  ('ICON_HD_SELECTION_BARBARIAN_SAPPER',    'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 4),
  ('ICON_HD_SELECTION_BARBARIAN_GOLD',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 5),
  ('ICON_HD_SELECTION_BARBARIAN_LUXURY',    'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 6),
  ('ICON_HD_SELECTION_BARBARIAN_STRATEGIC', 'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 7),
  ('ICON_HD_SELECTION_BARBARIAN_HEAL',      'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 8),
  ('ICON_HD_SELECTION_BARBARIAN_PROMOTION', 'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 9),
  ('ICON_HD_SELECTION_BARBARIAN_MOVEMENT',  'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 10),
  ('ICON_HD_SELECTION_BARBARIAN_BUILDER',   'ICON_ATLAS_HD_SCOTLAND_SELECTIONS', 11);