insert or ignore into IconTextureAtlases (Name, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',		  32,   6,  6,  'HD_CityState_Resources_32.dds'),
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',		  38,   6,  6,  'HD_CityState_Resources_38.dds'),
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',		  50,   6,  6,  'HD_CityState_Resources_50.dds'),
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',		  64,   6,  6,  'HD_CityState_Resources_64.dds'),
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',		  256,  6,  6,  'HD_CityState_Resources_256.dds'),
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',	256,  6,  6,  'HD_CityState_Resources_FOW_256.dds');

insert or ignore into IconTextureAtlases (Name, Baseline, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_CITYSTATE_RESOURCES_HD',  6,  22,   6,  6,  'HD_CityState_Resources_22.dds');

insert or replace into IconDefinitions (Name, Atlas, 'Index') values
  ('ICON_RESOURCE_HD_CS_MANUSCRIPT',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      0),
  ('ICON_RESOURCE_HD_CS_MANUSCRIPT_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  0),
  ('RESOURCE_HD_CS_MANUSCRIPT',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      0),
  
  ('ICON_RESOURCE_HD_CS_MEDICINAL_HERBS',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      1),
  ('ICON_RESOURCE_HD_CS_MEDICINAL_HERBS_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  1),
  ('RESOURCE_HD_CS_MEDICINAL_HERBS',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      1),
  
  ('ICON_RESOURCE_HD_CS_DIDACTIC_MATERIALS',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      2),
  ('ICON_RESOURCE_HD_CS_DIDACTIC_MATERIALS_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  2),
  ('RESOURCE_HD_CS_DIDACTIC_MATERIALS',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      2),
  
  ('ICON_RESOURCE_HD_CS_ASTROLABE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      3),
  ('ICON_RESOURCE_HD_CS_ASTROLABE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  3),
  ('RESOURCE_HD_CS_ASTROLABE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      3),
  
  ('ICON_RESOURCE_HD_CS_DANCE_COSTUME',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      4),
  ('ICON_RESOURCE_HD_CS_DANCE_COSTUME_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  4),
  ('RESOURCE_HD_CS_DANCE_COSTUME',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      4),
  
  ('ICON_RESOURCE_HD_CS_MUSICAL_INSTRUMENTS',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      5),
  ('ICON_RESOURCE_HD_CS_MUSICAL_INSTRUMENTS_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  5),
  ('RESOURCE_HD_CS_MUSICAL_INSTRUMENTS',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      5),
  
  ('ICON_RESOURCE_HD_CS_FLOWER_ARRANGEMENT',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      6),
  ('ICON_RESOURCE_HD_CS_FLOWER_ARRANGEMENT_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  6),
  ('RESOURCE_HD_CS_FLOWER_ARRANGEMENT',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      6),
  
  ('ICON_RESOURCE_HD_CS_TEA_SET',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      7),
  ('ICON_RESOURCE_HD_CS_TEA_SET_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  7),
  ('RESOURCE_HD_CS_TEA_SET',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      7),
  
  ('ICON_RESOURCE_HD_CS_CARAVAN',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      8),
  ('ICON_RESOURCE_HD_CS_CARAVAN_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  8),
  ('RESOURCE_HD_CS_CARAVAN',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      8),
  
  ('ICON_RESOURCE_HD_CS_STRUCK_COINAGE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      9),
  ('ICON_RESOURCE_HD_CS_STRUCK_COINAGE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  9),
  ('RESOURCE_HD_CS_STRUCK_COINAGE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      9),
  
  ('ICON_RESOURCE_HD_CS_EXOTIC_BEAST',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      10),
  ('ICON_RESOURCE_HD_CS_EXOTIC_BEAST_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  10),
  ('RESOURCE_HD_CS_EXOTIC_BEAST',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      10),
  
  ('ICON_RESOURCE_HD_CS_RARE_BIRD',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      11),
  ('ICON_RESOURCE_HD_CS_RARE_BIRD_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  11),
  ('RESOURCE_HD_CS_RARE_BIRD',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      11),
  
  ('ICON_RESOURCE_HD_CS_CANOPIED_CART',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      12),
  ('ICON_RESOURCE_HD_CS_CANOPIED_CART_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  12),
  ('RESOURCE_HD_CS_CANOPIED_CART',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      12),
  
  ('ICON_RESOURCE_HD_CS_MASTERWORK_SWORD',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      13),
  ('ICON_RESOURCE_HD_CS_MASTERWORK_SWORD_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  13),
  ('RESOURCE_HD_CS_MASTERWORK_SWORD',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      13),
  
  ('ICON_RESOURCE_HD_CS_DESTRIER',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      14),
  ('ICON_RESOURCE_HD_CS_DESTRIER_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  14),
  ('RESOURCE_HD_CS_DESTRIER',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      14),
  
  ('ICON_RESOURCE_HD_CS_ARMOR',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      15),
  ('ICON_RESOURCE_HD_CS_ARMOR_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  15),
  ('RESOURCE_HD_CS_ARMOR',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      15),
  
  ('ICON_RESOURCE_HD_CS_DEITY_STATUE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      16),
  ('ICON_RESOURCE_HD_CS_DEITY_STATUE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  16),
  ('RESOURCE_HD_CS_DEITY_STATUE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      16),
  
  ('ICON_RESOURCE_HD_CS_ROSARY',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      17),
  ('ICON_RESOURCE_HD_CS_ROSARY_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  17),
  ('RESOURCE_HD_CS_ROSARY',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      17),
  
  ('ICON_RESOURCE_HD_CS_SCRIPTURE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      18),
  ('ICON_RESOURCE_HD_CS_SCRIPTURE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  18),
  ('RESOURCE_HD_CS_SCRIPTURE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      18),
  
  ('ICON_RESOURCE_HD_CS_ORACLE_IMPLEMENTS',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      19),
  ('ICON_RESOURCE_HD_CS_ORACLE_IMPLEMENTS_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  19),
  ('RESOURCE_HD_CS_ORACLE_IMPLEMENTS',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      19),
  
  ('ICON_RESOURCE_HD_CS_ALMANAC',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      20),
  ('ICON_RESOURCE_HD_CS_ALMANAC_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  20),
  ('RESOURCE_HD_CS_ALMANAC',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      20),
  
  ('ICON_RESOURCE_HD_CS_YEAST',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      21),
  ('ICON_RESOURCE_HD_CS_YEAST_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  21),
  ('RESOURCE_HD_CS_YEAST',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      21),
  
  ('ICON_RESOURCE_HD_CS_RESIN',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      22),
  ('ICON_RESOURCE_HD_CS_RESIN_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  22),
  ('RESOURCE_HD_CS_RESIN',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      22),
  
  ('ICON_RESOURCE_HD_CS_CASK',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      23),
  ('ICON_RESOURCE_HD_CS_CASK_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  23),
  ('RESOURCE_HD_CS_CASK',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      23),
  
  ('ICON_RESOURCE_HD_CS_SEA_CHART',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      24),
  ('ICON_RESOURCE_HD_CS_SEA_CHART_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  24),
  ('RESOURCE_HD_CS_SEA_CHART',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      24),
  
  ('ICON_RESOURCE_HD_CS_FIGUREHEAD',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      25),
  ('ICON_RESOURCE_HD_CS_FIGUREHEAD_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  25),
  ('RESOURCE_HD_CS_FIGUREHEAD',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      25),
  
  ('ICON_RESOURCE_HD_CS_CANVAS',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      26),
  ('ICON_RESOURCE_HD_CS_CANVAS_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  26),
  ('RESOURCE_HD_CS_CANVAS',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      26),
  
  ('ICON_RESOURCE_HD_CS_YACHT',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      27),
  ('ICON_RESOURCE_HD_CS_YACHT_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  27),
  ('RESOURCE_HD_CS_YACHT',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      27),
  
  ('ICON_RESOURCE_HD_CS_TERRACOTTA',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      28),
  ('ICON_RESOURCE_HD_CS_TERRACOTTA_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  28),
  ('RESOURCE_HD_CS_TERRACOTTA',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      28),
  
  ('ICON_RESOURCE_HD_CS_MEASURING_INSTRUMENT',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      29),
  ('ICON_RESOURCE_HD_CS_MEASURING_INSTRUMENT_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  29),
  ('RESOURCE_HD_CS_MEASURING_INSTRUMENT',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      29),
  
  ('ICON_RESOURCE_HD_CS_RED_BRICK',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      30),
  ('ICON_RESOURCE_HD_CS_RED_BRICK_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  30),
  ('RESOURCE_HD_CS_RED_BRICK',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      30),
  
  ('ICON_RESOURCE_HD_CS_STEEL',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      31),
  ('ICON_RESOURCE_HD_CS_STEEL_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  31),
  ('RESOURCE_HD_CS_STEEL',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      31),
  
  ('ICON_RESOURCE_HD_CS_TIMEPIECE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      32),
  ('ICON_RESOURCE_HD_CS_TIMEPIECE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  32),
  ('RESOURCE_HD_CS_TIMEPIECE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      32),
  
  ('ICON_RESOURCE_HD_CS_SEWING_MACHINE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      33),
  ('ICON_RESOURCE_HD_CS_SEWING_MACHINE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  33),
  ('RESOURCE_HD_CS_SEWING_MACHINE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      33),
  
  ('ICON_RESOURCE_HD_CS_CANDLE',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      34),
  ('ICON_RESOURCE_HD_CS_CANDLE_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  34),
  ('RESOURCE_HD_CS_CANDLE',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      34),
  
  ('ICON_RESOURCE_HD_CS_WHITE_PAPER',      'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      35),
  ('ICON_RESOURCE_HD_CS_WHITE_PAPER_FOW',  'ICON_ATLAS_CITYSTATE_RESOURCES_HD_FOW',  35),
  ('RESOURCE_HD_CS_WHITE_PAPER',           'ICON_ATLAS_CITYSTATE_RESOURCES_HD',      35);